# Generated by Django 3.0.7 on 2020-07-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elec', '0003_contact_order_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
