# Generated by Django 3.0.7 on 2020-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goo_name', models.CharField(max_length=500)),
                ('category', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='elec/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
