# Generated by Django 3.0.7 on 2020-07-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec', '0007_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
