# Generated by Django 3.0.7 on 2020-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec', '0008_good_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sub_category1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='sub_category2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='sub_category3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='sub_category4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='good',
            name='sub_category5',
            field=models.CharField(default='', max_length=100),
        ),
    ]
