# Generated by Django 3.0.7 on 2020-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec', '0010_auto_20200726_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sub_category5',
        ),
        migrations.AddField(
            model_name='good',
            name='sub_category1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
